/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FestivalFactoryInterface extends Interface {
  getFunction(nameOrSignature: "createFestival" | "usdt"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FestivalCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createFestival",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createFestival",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
}

export namespace FestivalCreatedEvent {
  export type InputTuple = [
    token: AddressLike,
    vault: AddressLike,
    name: string,
    symbol: string
  ];
  export type OutputTuple = [
    token: string,
    vault: string,
    name: string,
    symbol: string
  ];
  export interface OutputObject {
    token: string;
    vault: string;
    name: string;
    symbol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FestivalFactory extends BaseContract {
  connect(runner?: ContractRunner | null): FestivalFactory;
  waitForDeployment(): Promise<this>;

  interface: FestivalFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createFestival: TypedContractMethod<
    [
      name: string,
      symbol: string,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [[string, string] & { token: string; vault: string }],
    "nonpayable"
  >;

  usdt: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createFestival"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [[string, string] & { token: string; vault: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FestivalCreated"
  ): TypedContractEvent<
    FestivalCreatedEvent.InputTuple,
    FestivalCreatedEvent.OutputTuple,
    FestivalCreatedEvent.OutputObject
  >;

  filters: {
    "FestivalCreated(address,address,string,string)": TypedContractEvent<
      FestivalCreatedEvent.InputTuple,
      FestivalCreatedEvent.OutputTuple,
      FestivalCreatedEvent.OutputObject
    >;
    FestivalCreated: TypedContractEvent<
      FestivalCreatedEvent.InputTuple,
      FestivalCreatedEvent.OutputTuple,
      FestivalCreatedEvent.OutputObject
    >;
  };
}
