/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { FestivalFactory } from "./FestivalFactory";
export type { FestivalToken } from "./FestivalToken";
export type { FestivalVault } from "./FestivalVault";
export type { TestUSDT } from "./TestUSDT";
